[pytest]
DJANGO_SETTINGS_MODULE = project.settings
python_files = test.py tests.py test_*.py tests_*.py *_test.py *_tests.py
# Resumo final dos testes (exceto os que passaram)
# Mostra prints durante execução
#   --capture=no <- mostra prints
addopts = 
  --doctest-modules
  --strict-markers
  -ra
  -v
markers =
  slow: Run tests that are slow
  fast: Run fast tests