[pytest]
# Django settings module to use for testing
#pytest-django will automatically set the DJANGO_SETTINGS_MODULE environment variable to this value when running tests.

DJANGO_SETTINGS_MODULE = project.settings
python_files = test.py tests.py test_*.py tests_*.py *_test.py *_tests.py

# --doctest-modules <- executa testes de docstrings
# --strict-markers <- força a declaração de marcadores no arquivo pytest.ini
# --capture=no <- mostra prints no terminal
# -ra <- mostra resumo final dos testes (exceto os que passaram)
# -v  <- verbose <- mostra detalhes de cada teste
# --cov-report=html <- gera relatório de cobertura em HTML
# --cov-report=term-missing <- mostra cobertura no terminal, incluindo linhas não cobertas
# --cov=recipes <- pasta a ser analisada para cobertura de testes
addopts = 
  --doctest-modules
  --strict-markers
  -ra
  ; --cov=recipes
  --cov-report=term-missing
  --cov-report=html
  -v
  --capture=no

# Marcadores para categorizar os testes
# Usar --markers para visualizar os marcadores disponíveis
# @pytest.mark.slow <- para testes lentos
# @pytest.mark.fast <- para testes rápidos
markers =
  slow: Run tests that are slow
  fast: Run fast tests